name: release

on: 
  push:
      tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - 
      name: Build package
      run: |
        go build -v ./...
        
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - 
      name: Test package
      run: |
        go test -v ./...
        
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@master
    - 
      name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "Automatic Release"

  add-builds:
    needs: [release]
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          - goarch: "386"
            goos: darwin

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: create go binaries
      uses: wangyoucao577/go-release-action@v1.16
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: LICENSE README.md
        sha256sum: true
        md5sum: false